GET  http://localhost:5000/users

###
GET  http://localhost:5000/users/1


###
POST http://localhost:5000/users/create
Content-Type: application/json

{
    "name": "Udin",
    "email": "udin@gmail.com",
    "gender": "Male"
}

###
PATCH  http://localhost:5000/users/update/1
Content-Type: application/json

{
    "name": "Andini",
    "email": "andini@gmail.com",
    "gender": "Male"
}


###
DELETE  http://localhost:5000/users/delete/2
